FROM python:3.12.6-slim-bookworm

RUN useradd -ms /bin/bash celery
WORKDIR /src
COPY  techsiro/requirments src/requirements


RUN apt-get update && \
    apt-get install -y libpq-dev && \
    pip install --upgrade pip && \
    pip install -r src/requirements/dev.requirements.txt

RUN chown -R celery:celery /src        
USER celery

COPY . /src
CMD [ "celery","-A","projectApps.core","worker","-l","info" ]


